name = "quantum-wave-simulation"
compatibility_date = "2026-01-20"
pages_build_output_dir = "./"

[site]
bucket = "./"

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.js", "**/*.jsx"]
fallthrough = true
